#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "espocrm"
name = "EspoCRM"
description.en = "Customer Relationship Management application"
description.fr = "Application de gestion des relations avec les clients"

version = "10.0.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
website = "https://www.espocrm.com"
demo = "https://www.espocrm.com/demo/"
admindoc = "https://docs.espocrm.com/"
code = "https://github.com/espocrm/espocrm"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/espocrm/espocrm/archive/refs/tags/10.0.1.tar.gz"
    sha256 = "7d8947df6e8a00fee668e2d30c9a7518f24837c6a1077546aa34776a112d9aa8"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.apt]
    packages = "mariadb-server, php8.5-xml, php8.5-gd, php8.5-bcmath, php8.5-zip, php8.5-mbstring, php8.5-curl, php8.5-mysql, php8.5-imap, php8.5-exif, php8.5-ldap"

    [resources.database]
    type = "mysql"
